import Foundation
@testable import SneekLib

func runScriptGeneratorTests() {
    print("\nScriptGenerator:")

    test("Generate script for a command") {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("sneek-test-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: tempDir) }

        let outputDir = tempDir.appendingPathComponent("bin").path
        let cmd = CommandConfig(name: "my-db", description: "Connect to DB", mode: .oneshot, command: "psql")

        let path = try ScriptGenerator.generate(command: cmd, outputDir: outputDir)

        check(path == outputDir + "/my-db", "path is \(path)")

        let content = try String(contentsOfFile: path, encoding: .utf8)
        check(content.hasPrefix("#!/bin/bash\n"), "starts with shebang")
        check(content.contains("exec sneekd run my-db \"$@\""), "has exec line")
        check(content.contains("generated by Sneek"), "has generated comment")

        let attrs = try FileManager.default.attributesOfItem(atPath: path)
        let perms = (attrs[.posixPermissions] as! NSNumber).intValue
        check(perms == 0o755, "permissions are 0755, got \(String(perms, radix: 8))")
    }

    test("generateAll for multiple commands") {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("sneek-test-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: tempDir) }

        let store = try ConfigStore(baseDir: tempDir.appendingPathComponent("config"))
        try store.save(CommandConfig(name: "cmd-a", description: "A", mode: .oneshot, command: "echo a"))
        try store.save(CommandConfig(name: "cmd-b", description: "B", mode: .session, command: "echo b"))

        let outputDir = tempDir.appendingPathComponent("bin").path
        let paths = try ScriptGenerator.generateAll(configStore: store, outputDir: outputDir)

        check(paths.count == 2, "expected 2 scripts, got \(paths.count)")
        for p in paths {
            check(FileManager.default.fileExists(atPath: p), "script exists at \(p)")
        }

        let names = Set(paths.map { URL(fileURLWithPath: $0).lastPathComponent })
        check(names.contains("cmd-a"), "has cmd-a")
        check(names.contains("cmd-b"), "has cmd-b")
    }

    test("installMCP creates settings file when it doesn't exist") {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("sneek-test-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: tempDir) }

        let settingsPath = tempDir.appendingPathComponent("settings.json").path

        try ScriptGenerator.installMCP(sneekdPath: "/usr/local/bin/sneekd", settingsPath: settingsPath)

        let data = try Data(contentsOf: URL(fileURLWithPath: settingsPath))
        let root = try JSONSerialization.jsonObject(with: data) as! [String: Any]
        let mcpServers = root["mcpServers"] as! [String: Any]
        let sneek = mcpServers["sneek"] as! [String: Any]
        check(sneek["command"] as? String == "/usr/local/bin/sneekd", "command path")
        let args = sneek["args"] as? [String]
        check(args == ["mcp-serve"], "args is mcp-serve")
    }

    test("installMCP preserves existing settings") {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("sneek-test-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: tempDir) }
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

        let settingsPath = tempDir.appendingPathComponent("settings.json").path
        let existing: [String: Any] = [
            "mcpServers": ["other-tool": ["command": "/bin/other", "args": []]],
            "someKey": "someValue"
        ]
        let existingData = try JSONSerialization.data(withJSONObject: existing, options: .prettyPrinted)
        try existingData.write(to: URL(fileURLWithPath: settingsPath))

        try ScriptGenerator.installMCP(sneekdPath: "/opt/sneekd", settingsPath: settingsPath)

        let data = try Data(contentsOf: URL(fileURLWithPath: settingsPath))
        let root = try JSONSerialization.jsonObject(with: data) as! [String: Any]

        check(root["someKey"] as? String == "someValue", "preserved someKey")

        let mcpServers = root["mcpServers"] as! [String: Any]
        let otherTool = mcpServers["other-tool"] as? [String: Any]
        check(otherTool?["command"] as? String == "/bin/other", "preserved other-tool")

        let sneek = mcpServers["sneek"] as! [String: Any]
        check(sneek["command"] as? String == "/opt/sneekd", "sneek command updated")
    }
}
