import Foundation

public enum ScriptGenerator {
    /// Generate shell wrapper scripts for all commands in the config store.
    /// Scripts go to the specified output directory.
    public static func generateAll(configStore: ConfigStore, outputDir: String) throws -> [String] {
        var paths: [String] = []
        for command in configStore.commands.values {
            let path = try generate(command: command, outputDir: outputDir)
            paths.append(path)
        }
        return paths
    }

    /// Generate a single shell script for a command.
    public static func generate(command: CommandConfig, outputDir: String) throws -> String {
        let fm = FileManager.default
        let dir = URL(fileURLWithPath: outputDir)
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)

        let scriptPath = dir.appendingPathComponent(command.name).path
        let content = """
            #!/bin/bash
            # \(outputDir)/\(command.name) — generated by Sneek (do not edit)
            exec sneekd run \(command.name) "$@"
            """

        try content.write(toFile: scriptPath, atomically: true, encoding: .utf8)
        try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: scriptPath)
        return scriptPath
    }

    /// Add/update the sneek MCP server entry in Claude Code's settings.
    public static func installMCP(sneekdPath: String, settingsPath: String) throws {
        let fm = FileManager.default
        var root: [String: Any]

        if fm.fileExists(atPath: settingsPath) {
            let data = try Data(contentsOf: URL(fileURLWithPath: settingsPath))
            guard let parsed = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                throw ScriptGeneratorError.invalidSettingsJSON
            }
            root = parsed
        } else {
            let parentDir = URL(fileURLWithPath: settingsPath).deletingLastPathComponent()
            try fm.createDirectory(at: parentDir, withIntermediateDirectories: true)
            root = [:]
        }

        var mcpServers = root["mcpServers"] as? [String: Any] ?? [:]
        mcpServers["sneek"] = ["command": sneekdPath, "args": ["mcp-serve"]]
        root["mcpServers"] = mcpServers

        let data = try JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys])
        try data.write(to: URL(fileURLWithPath: settingsPath))
    }
}

enum ScriptGeneratorError: Error {
    case invalidSettingsJSON
}
